import type { Metadata } from "next";
import React from 'react';
import localFont from 'next/font/local';
import './globals.scss';

const neueMontreal = localFont({
  src: [
    { path: './fonts/PP_Neue_Montreal/PPNeueMontreal-Thin.otf', weight: '100', style: 'normal' },
    { path: './fonts/PP_Neue_Montreal/PPNeueMontreal-Book.otf', weight: '400', style: 'normal' },
    { path: './fonts/PP_Neue_Montreal/PPNeueMontreal-Italic.otf', weight: '400', style: 'italic' },
    { path: './fonts/PP_Neue_Montreal/PPNeueMontreal-Medium.otf', weight: '500', style: 'normal' },
    { path: './fonts/PP_Neue_Montreal/PPNeueMontreal-SemiBolditalic.otf', weight: '600', style: 'italic' },
    { path: './fonts/PP_Neue_Montreal/PPNeueMontreal-Bold.otf', weight: '700', style: 'normal' },
  ],
  variable: '--font-sans',
});

const zagmaMono = localFont({
  src: [
    { path: './fonts/Zagma_Mono/F37ZagmaMonoTrial-Light.otf', weight: '300', style: 'normal' },
    { path: './fonts/Zagma_Mono/F37ZagmaMonoTrial-LightItalic.otf', weight: '300', style: 'italic' },
    { path: './fonts/Zagma_Mono/F37ZagmaMonoTrial-Book.otf', weight: '350', style: 'normal' },
    { path: './fonts/Zagma_Mono/F37ZagmaMonoTrial-BookItalic.otf', weight: '350', style: 'italic' },
    { path: './fonts/Zagma_Mono/F37ZagmaMonoTrial-Regular.otf', weight: '400', style: 'normal' },
    { path: './fonts/Zagma_Mono/F37ZagmaMonoTrial-RegularItalic.otf', weight: '400', style: 'italic' },
    { path: './fonts/Zagma_Mono/F37ZagmaMonoTrial-Bold.otf', weight: '700', style: 'normal' },
    { path: './fonts/Zagma_Mono/F37ZagmaMonoTrial-BoldItalic.otf', weight: '700', style: 'italic' },
  ],
  variable: '--font-mono',
});

export const metadata: Metadata = {
  title: "Qoves Inc. - Test Task",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={`${neueMontreal.variable} ${zagmaMono.variable}`}>
      <body>{children}</body>
    </html>
  );
}